// Enrich a Single Attacker IP with Geolocation
// Uses the ipv4_lookup function alongside the "geoip" Watchlist to enrich a
// specific attacker's IP address with geographic data.

let GeoIPDB_FULL = _GetWatchlist("geoip");
let WindowsEvents = SecurityEvent
    | where IpAddress == '124.123.192.35'
    | where EventID == 4625
    | order by TimeGenerated desc
    | evaluate ipv4_lookup(GeoIPDB_FULL, IpAddress, network);
WindowsEvents
| project TimeGenerated, Computer, AttackerIP = IpAddress, cityname, countryname, latitude, longitude
